In [1]:
import pandas as pd

In [4]:
interactions = pd.read_csv('data/to_sql/interactions.csv')
recipes = pd.read_csv('data/to_sql/recipes.csv')

In [5]:
interactions.head()

   Unnamed: 0   user_id  recipe_id  rating
0           0   8542392     222388       5
1           1  11174581     222388       5
2           2   8262477     222388       5
3           3   3574785     240488       5
4           4  12145410     240488       2

In [6]:
recipes.head()

,Unnamed: 0,recipe_id,recipe_name,aver_rate,review_nums,ingredients
0,0,222388,Homemade Bacon,5.000000,3,"['pork belly', 'smoked paprika', 'kosher salt'..."
1,1,240488,"Pork Loin, Apples, and Sauerkraut",4.764706,29,"['sauerkraut drained', 'Granny Smith apples sl..."
2,2,218939,Foolproof Rosemary Chicken Wings,4.571429,12,"['chicken wings', 'sprigs rosemary', 'head gar..."
3,3,87211,Chicken Pesto Paninis,4.625000,163,"['focaccia bread quartered', 'prepared basil p..."
4,4,245714,Potato Bacon Pizza,4.500000,2,"['red potatoes', 'strips bacon', 'Sauce:', 'he..."

In [7]:
interactions_recipes_temp = pd.merge(interactions, recipes, how='left', on='recipe_id')

In [8]:
interactions_recipes_temp.head(200)

,Unnamed: 0_x,user_id,recipe_id,rating,Unnamed: 0_y,recipe_name,aver_rate,review_nums,ingredients
0,0,8542392,222388,5,0,Homemade Bacon,5.000000,3,"['pork belly', 'smoked paprika', 'kosher salt'..."
1,1,11174581,222388,5,0,Homemade Bacon,5.000000,3,"['pork belly', 'smoked paprika', 'kosher salt'..."
2,2,8262477,222388,5,0,Homemade Bacon,5.000000,3,"['pork belly', 'smoked paprika', 'kosher salt'..."
3,3,3574785,240488,5,1,"Pork Loin, Apples, and Sauerkraut",4.764706,29,"['sauerkraut drained', 'Granny Smith apples sl..."
4,4,12145410,240488,2,1,"Pork Loin, Apples, and Sauerkraut",4.764706,29,"['sauerkraut drained', 'Granny Smith apples sl..."
...,...,...,...,...,...,...,...,...,...
195,195,743666,87211,5,3,Chicken Pesto Paninis,4.625000,163,"['focaccia bread quartered', 'prepared basil p..."
196,196,2868211,87211,5,3,Chicken Pesto Paninis,4.625000,163,"['focaccia bread quartered', 'prepared basil p..."
197,197,2549374,87211,4,3,Chicken Pesto Paninis,4.625000,163,"['focaccia bread quartered', 'prepared basil p..."
198,198,9648389,87211,5,3,Chicken Pesto Paninis,4.625000,163,"['focaccia bread quartered', 'prepared basil p..."
199,199,4610345,87211,5,3,Chicken Pesto Paninis,4.625000,163,"['focaccia bread quartered', 'prepared basil p..."